### ISSUE TITLE
Request License Button on Self Hosted is broken

### ISSUE THREAD

**Issue by JohannesLandgraf** [gitpod-io/website-kumquat#316] opened 2021-04-08 08:14 UTC
<img width="445" alt="CleanShot 2021-04-08 at 10 13 42@2x" src="https://user-images.githubusercontent.com/22498066/113991828-1e1f3000-9853-11eb-92e3-0b6b27547dc2.png">

**Comment by mikenikles** [comment] 2021-04-11 20:47
Duplicate of #304

**Closed by mikenikles** 2021-04-11 20:47 UTC
Labels: go-live
